import { ApiKeys } from "@/types/keys"
import type { AIModel } from "@/types/models"
import {
  RiRobotLine,
  RiBrainLine,
  RiFlashlightLine,
  RiSearchLine,
  RiFireLine,
  RiMapLine,
  RiVipCrownLine,
  RiImageLine,
  RiCpuLine,
  RiCircleLine,
  RiStarLine,
  RiRocketLine,
  RiMusicLine,
  RiPuzzleLine,
  RiLightbulbLine,
  RiCodeLine,
  RiCalendarLine,
  RiFlaskLine,
  RiEyeLine,
  RiEmotionHappyLine,
  RiQuestionLine,
  RiTranslate,
  RiSpeedLine,
  RiLeafLine,
  RiGamepadLine,
  RiStarSLine,
  RiMiniProgramLine,
} from "react-icons/ri"

export const AI_MODELS: AIModel[] = [
  
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    category: "text",
    icon: RiSpeedLine,
    color: "bg-blue-500",
    description: "Fast and efficient for everyday tasks",
    requiresKey: "google",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    category: "text",
    icon: RiVipCrownLine,
    color: "bg-blue-600",
    description: "Advanced reasoning and complex tasks",
    requiresKey: "google",
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    category: "text",
    icon: RiFlashlightLine,
    color: "bg-blue-400",
    description: "Balanced speed and capability",
    requiresKey: "google",
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    provider: "Google",
    category: "text",
    icon: RiLeafLine,
    color: "bg-blue-300",
    description: "Lightweight and fast responses",
    requiresKey: "google",
  },
  {
    id: "gemini-2.5-flash-thinking",
    name: "Gemini 2.5 Flash (Thinking)",
    provider: "Google",
    category: "reasoning",
    icon: RiBrainLine,
    color: "bg-purple-500",
    description: "Enhanced reasoning capabilities",
    requiresKey: "google",
  },

  
  {
    id: "gpt-imagegen",
    name: "GPT ImageGen",
    provider: "OpenAI",
    category: "image",
    icon: RiImageLine,
    color: "bg-green-500",
    description: "AI-powered image generation",
    requiresKey: "openai",
  },
  {
    id: "gpt-4.1",
    name: "GPT 4.1",
    provider: "OpenAI",
    category: "text",
    icon: RiRobotLine,
    color: "bg-green-600",
    description: "Latest GPT model with enhanced capabilities",
    requiresKey: "openai",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT 4.1 Mini",
    provider: "OpenAI",
    category: "text",
    icon: RiCpuLine,
    color: "bg-green-400",
    description: "Compact version of GPT 4.1",
    requiresKey: "openai",
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT 4.1 Nano",
    provider: "OpenAI",
    category: "text",
    icon: RiMiniProgramLine,
    color: "bg-green-300",
    description: "Ultra-lightweight GPT model",
    requiresKey: "openai",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT 4o-mini",
    provider: "OpenAI",
    category: "text",
    icon: RiCircleLine,
    color: "bg-green-400",
    description: "Optimized mini version",
    requiresKey: "openai",
  },
  {
    id: "gpt-4o",
    name: "GPT 4o",
    provider: "OpenAI",
    category: "text",
    icon: RiStarLine,
    color: "bg-green-500",
    description: "Omni-modal GPT model",
    requiresKey: "openai",
  },
  {
    id: "gpt-4.5",
    name: "GPT 4.5",
    provider: "OpenAI",
    category: "text",
    icon: RiRocketLine,
    color: "bg-green-700",
    description: "Next generation GPT model",
    requiresKey: "openai",
  },

  
  {
    id: "claude-4-sonnet",
    name: "Claude 4 Sonnet",
    provider: "Anthropic",
    category: "text",
    icon: RiMusicLine,
    color: "bg-orange-500",
    description: "Balanced performance and speed",
    requiresKey: "anthropic",
  },
  {
    id: "claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    category: "text",
    icon: RiMusicLine,
    color: "bg-orange-400",
    description: "Enhanced reasoning and analysis",
    requiresKey: "anthropic",
  },
  {
    id: "claude-3.7-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    category: "text",
    icon: RiMusicLine,
    color: "bg-orange-600",
    description: "Advanced language understanding",
    requiresKey: "anthropic",
  },
  {
    id: "claude-3.7-sonnet-reasoning",
    name: "Claude 3.7 Sonnet (Reasoning)",
    provider: "Anthropic",
    category: "reasoning",
    icon: RiPuzzleLine,
    color: "bg-purple-600",
    description: "Specialized for complex reasoning",
    requiresKey: "anthropic",
  },
  {
    id: "claude-4-opus",
    name: "Claude 4 Opus",
    provider: "Anthropic",
    category: "text",
    icon: RiVipCrownLine,
    color: "bg-orange-700",
    description: "Most capable Claude model",
    requiresKey: "anthropic",
  },

  
  {
    id: "o4-mini",
    name: "o4 mini",
    provider: "OpenAI",
    category: "reasoning",
    icon: RiLightbulbLine,
    color: "bg-yellow-500",
    description: "Compact reasoning model",
    requiresKey: "openai",
  },
  {
    id: "o3-mini",
    name: "o3 mini",
    provider: "OpenAI",
    category: "reasoning",
    icon: RiPuzzleLine,
    color: "bg-yellow-400",
    description: "Efficient reasoning capabilities",
    requiresKey: "openai",
  },
  {
    id: "o3",
    name: "o3",
    provider: "OpenAI",
    category: "reasoning",
    icon: RiBrainLine,
    color: "bg-yellow-600",
    description: "Advanced reasoning model",
    requiresKey: "openai",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    category: "reasoning",
    icon: RiSearchLine,
    color: "bg-red-500",
    description: "Deep reasoning capabilities",
    requiresKey: "deepseek",
  },
  {
    id: "deepseek-v3-fireworks",
    name: "DeepSeek v3 (Fireworks)",
    provider: "Fireworks",
    category: "text",
    icon: RiFireLine,
    color: "bg-red-400",
    description: "High-performance inference",
    requiresKey: "fireworks",
  },
  {
    id: "deepseek-v3-0324",
    name: "DeepSeek v3 (0324)",
    provider: "DeepSeek",
    category: "text",
    icon: RiCodeLine,
    color: "bg-red-600",
    description: "Code-optimized model",
    requiresKey: "deepseek",
  },
  {
    id: "deepseek-r1-openrouter",
    name: "DeepSeek R1 (OpenRouter)",
    provider: "OpenRouter",
    category: "reasoning",
    icon: RiMapLine,
    color: "bg-indigo-500",
    description: "Reasoning via OpenRouter",
    requiresKey: "openrouter",
  },
  {
    id: "deepseek-r1-0528",
    name: "DeepSeek R1 (0528)",
    provider: "DeepSeek",
    category: "reasoning",
    icon: RiCalendarLine,
    color: "bg-red-700",
    description: "Latest reasoning checkpoint",
    requiresKey: "deepseek",
  },
  {
    id: "deepseek-r1-owen",
    name: "DeepSeek R1 (Owen Distilled)",
    provider: "DeepSeek",
    category: "reasoning",
    icon: RiFlaskLine,
    color: "bg-red-300",
    description: "Distilled reasoning model",
    requiresKey: "deepseek",
  },
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70b",
    provider: "Meta",
    category: "text",
    icon: RiStarSLine,
    color: "bg-blue-700",
    description: "Large language model by Meta",
    requiresKey: "groq",
  },
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    provider: "Meta",
    category: "text",
    icon: RiEyeLine,
    color: "bg-blue-800",
    description: "Exploration-focused model",
    requiresKey: "groq",
  },
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    provider: "Meta",
    category: "text",
    icon: RiGamepadLine,
    color: "bg-blue-900",
    description: "Independent reasoning model",
    requiresKey: "groq",
  },
  {
    id: "grok-3",
    name: "Grok 3",
    provider: "xAI",
    category: "text",
    icon: RiEmotionHappyLine,
    color: "bg-gray-600",
    description: "Humorous and witty AI",
    requiresKey: "groq",
  },
  {
    id: "grok-3-mini",
    name: "Grok 3 Mini",
    provider: "xAI",
    category: "text",
    icon: RiEmotionHappyLine,
    color: "bg-gray-500",
    description: "Compact version of Grok",
    requiresKey: "groq",
  },
  {
    id: "qwen-qwq-32b",
    name: "Qwen qwq-32b",
    provider: "Alibaba",
    category: "reasoning",
    icon: RiQuestionLine,
    color: "bg-teal-500",
    description: "Question-answering specialist",
    requiresKey: "openrouter",
  },
  {
    id: "qwen-2.5-32b",
    name: "Qwen 2.5 32b",
    provider: "Alibaba",
    category: "text",
    icon: RiTranslate,
    color: "bg-teal-600",
    description: "Multilingual capabilities",
    requiresKey: "openrouter",
  },
]

export const getModelsByCategory = (category?: string) => {
  if (!category) return AI_MODELS
  return AI_MODELS.filter((model) => model.category === category)
}

export const getModelsByProvider = (provider: string) => {
  return AI_MODELS.filter((model) => model.provider === provider)
}

export const getAvailableModels = (keys: ApiKeys) => {
  return AI_MODELS.filter((model) => {
    const requiredKey = keys[model.requiresKey]
    return requiredKey && requiredKey.trim() !== ""
  })
}
